name: radical-telehealth-collective

services:
  appserver:
    type: compose

    services:
      image: acobster/lando-clojure:cli-tools
      command: clojure -A:dev -m rtc.app

      environment:
        # `dbhost` corresponds with the dbhost service
        # `rtc` corresponds with dbhost.creds.database
        - DATABASE_URL=jdbc:postgresql://dbhost/rtc?user=postgres

      depends_on:
        - dbhost

      ports:
        - '7000:7000'

  dbhost:
    type: postgres:11
    creds:
      database: rtc

  nginx:
    type: nginx:1.14
    webroot: resources/public
    ssl: true

    config:
      server: lando/nginx.conf

    overrides:
      depends_on:
        - appserver

tooling:
  clojure:
    service: appserver
    cmd: clojure

  test:
    service: appserver
    cmd: clojure -A:dev -m kaocha.runner

proxy:
  nginx:
    # This tells Lando to forward requests on port 80 requests to 8080
    # inside the appserver container
    - radical-telehealth-collective.lndo.site
    # For developing when offline. You will need an entry in your hosts file
    # or something more advanced, such as dnsmasq, to resolve this URL
    - radical-telehealth-collective.local
